annotations:
  category: Database
  images: |
    - name: kubectl
      image: swr.cn-east-3.myhuaweicloud.com/cjldw/kubectl:1.31.1-debian-12-r1
    - name: os-shell
      image: swr.cn-east-3.myhuaweicloud.com/cjldw/os-shell:12-debian-12-r30
    - name: redis
      image: swr.cn-east-3.myhuaweicloud.com/cjldw/redis:7.4.0-debian-12-r4
    - name: redis-exporter
      image: swr.cn-east-3.myhuaweicloud.com/cjldw/redis-exporter:1.63.0-debian-12-r0
    - name: redis-sentinel
      image: swr.cn-east-3.myhuaweicloud.com/cjldw/redis-sentinel:7.4.0-debian-12-r5
  licenses: Apache-2.0
apiVersion: v2
appVersion: 7.4.0
dependencies:
- name: common
  repository: oci://swr.cn-east-3.myhuaweicloud.cm/cjldw
  tags:
  - bitnami-common
  version: 2.x.x
description: Redis(R) is an open source, advanced key-value store. It is often referred
  to as a data structure server since keys can contain strings, hashes, lists, sets
  and sorted sets.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
keywords:
- redis
- keyvalue
- database
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: redis
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/redis
version: 20.1.3
